# .gitpod.yml
tasks:
  - name: Install Dependencies
    init: npm install
    command: echo "Dependencies installed"

# Specify the ports you want to expose if any
ports:
  - port: 3000
    onOpen: open-preview

# Optional: Specify the editor configuration
vscode:
  extensions:
    - dbaeumer.vscode-eslint

# Optional: Prebuilds to speed up start time
prebuilds:
  - init: npm install
